language: php

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - php: 5.4
    - php: 5.4
      env:
        - BCMATH="off"
    - php: 5.5
    - php: 5.5
      env:
        - BCMATH="off"
    - php: 5.6
    - php: 5.6
      env:
        - BCMATH="off"
    - php: 7.0
    - php: 7.0
      env:
        - BCMATH="off"
    - php: 7.1
      env:
        - TEST_COVERAGE=true
    - php: 7.1
      env:
        - BCMATH="off"
    - php: nightly
    - php: hhvm

sudo: false

before_install:
  - if [[ $BCMATH == "off" ]]; then
        export PHP_BUILD_CONFIGURE_OPTS="--disable-bcmath";
        git clone git://github.com/php-build/php-build.git $HOME/.phpenv/plugins/php-build;
        travis_wait phpenv install --force `php -r "echo PHP_VERSION;"`;
        phpenv rehash;
        phpenv global `php -r "echo PHP_VERSION;"`;
    fi
  - if [[ $TEST_COVERAGE != 'true' && "$(php --version | grep xdebug -ci)" -ge 1 ]]; then phpenv config-rm xdebug.ini ; fi
  - php -i | grep bcmath

install:
  - travis_retry composer install --no-interaction --prefer-dist

before_script:
  - mkdir -p build/logs

script:
  - ./vendor/bin/parallel-lint src tests
  - ./vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml
  - ./vendor/bin/phpcs src tests --standard=psr2 -sp

after_script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then php vendor/bin/coveralls ; fi
